baseurl: "https://gilda.fundor333.com/"
title: Gilda dei Fledgling
languageCode: it
defaultContentLanguage: it

theme: "dnd_guild"

taxonomies:
  category: "categories"
  tag: "tags"
  razza: "razza"
  titolo: "titolo"
  spazio: "spazio"

menu:
  main:
    - name: Home
      pre: fa-house-turret
      url: /
      weight: 1
    - name: Membri
      pre: fa-people
      url: /membro/
      weight: 2
    - name: Corsi
      pre: fa-book-open
      url: /corso/
      weight: 3
    - name: Spazi della Gilda
      pre: fa-door-open
      url: /spazio/
      weight: 4
