baseurl: "https://gilda.fundor333.com/"
title: Gilda dei Fledgling
languageCode: it
defaultContentLanguage: it

theme: "dnd_guild"

taxonomies:
  category: "categories"
  tag: "tags"
  razza: "razza"
  titolo: "titolo"
  spazio: "spazio"

menu:
  main:
    - name: Home
      pre: fa-house-turret
      url: /
      weight: 1
    - name: Membri
      pre: fa-people
      url: /membro/
      weight: 2
    - name: Corsi
      pre: fa-book-open
      url: /corso/
      weight: 3
    - name: Spazi della Gilda
      pre: fa-door-open
      url: /spazio/
      weight: 4
    - name: Bacheca delle Quest
      pre: fa-map-pin
      url: /quest/
      weight: 5
    - name: Contatti
      pre: fa-address-book
      url: /personaggio/
      weight: 6
    - name: Bestiario
      pre: fa-dragon
      url: /bestiario/
      weight: 7
    - name: Lore
      pre: fa-book
      url: /lore/
      weight: 8
