baseurl: "https://gilda.fundor333.com/"
title: Gilda dei Fledgling
languageCode: it
defaultContentLanguage: it

theme: "dnd_guild"

menu:
  main:
    - name: Home
      pre: fa-house-turret
      url: /
      weight: 1
    - name: Membri
      pre: fa-people
      url: /membro/
      weight: 2

taxonomies:
  category: "categories"
  tag: "tags"
  razza: "razza"
  titolo: "titolo"
  spazio: "spazio"
